<?php
/**
 * TenantFilesInfoApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aurigma\AssetStorage\ApiException;
use Aurigma\AssetStorage\Configuration;
use Aurigma\AssetStorage\HeaderSelector;
use Aurigma\AssetStorage\ObjectSerializer;

/**
 * TenantFilesInfoApi Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TenantFilesInfoApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'tenantFilesInfoGetTenantFilesInfos' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation tenantFilesInfoGetTenantFilesInfos
     *
     * Returns information about file storage usage for the specified time period.
     *
     * @param  \DateTime $start_time Start date in UTC time format. (optional)
     * @param  \DateTime $end_time End date in UTC time format. If not specified, the current UTC time is used by default. (optional)
     * @param  int $granularity_options_days Number of days per group.  Set to &#x60;0&#x60; to keep the original array unchanged. (optional)
     * @param  \Aurigma\AssetStorage\Model\GranularityStrategyType $granularity_options_strategy Granularity calculation strategy. (optional)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tenantFilesInfoGetTenantFilesInfos'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aurigma\AssetStorage\Model\TenantFilesInfoDto[]
     */
    public function tenantFilesInfoGetTenantFilesInfos($start_time = null, $end_time = null, $granularity_options_days = null, $granularity_options_strategy = null, $tenant_id = null, string $contentType = self::contentTypes['tenantFilesInfoGetTenantFilesInfos'][0])
    {
        list($response) = $this->tenantFilesInfoGetTenantFilesInfosWithHttpInfo($start_time, $end_time, $granularity_options_days, $granularity_options_strategy, $tenant_id, $contentType);
        return $response;
    }

    /**
     * Operation tenantFilesInfoGetTenantFilesInfosWithHttpInfo
     *
     * Returns information about file storage usage for the specified time period.
     *
     * @param  \DateTime $start_time Start date in UTC time format. (optional)
     * @param  \DateTime $end_time End date in UTC time format. If not specified, the current UTC time is used by default. (optional)
     * @param  int $granularity_options_days Number of days per group.  Set to &#x60;0&#x60; to keep the original array unchanged. (optional)
     * @param  \Aurigma\AssetStorage\Model\GranularityStrategyType $granularity_options_strategy Granularity calculation strategy. (optional)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tenantFilesInfoGetTenantFilesInfos'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\AssetStorage\Model\TenantFilesInfoDto[], HTTP status code, HTTP response headers (array of strings)
     */
    public function tenantFilesInfoGetTenantFilesInfosWithHttpInfo($start_time = null, $end_time = null, $granularity_options_days = null, $granularity_options_strategy = null, $tenant_id = null, string $contentType = self::contentTypes['tenantFilesInfoGetTenantFilesInfos'][0])
    {
        $request = $this->tenantFilesInfoGetTenantFilesInfosRequest($start_time, $end_time, $granularity_options_days, $granularity_options_strategy, $tenant_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tenantFilesInfoGetTenantFilesInfosAsync
     *
     * Returns information about file storage usage for the specified time period.
     *
     * @param  \DateTime $start_time Start date in UTC time format. (optional)
     * @param  \DateTime $end_time End date in UTC time format. If not specified, the current UTC time is used by default. (optional)
     * @param  int $granularity_options_days Number of days per group.  Set to &#x60;0&#x60; to keep the original array unchanged. (optional)
     * @param  \Aurigma\AssetStorage\Model\GranularityStrategyType $granularity_options_strategy Granularity calculation strategy. (optional)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tenantFilesInfoGetTenantFilesInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tenantFilesInfoGetTenantFilesInfosAsync($start_time = null, $end_time = null, $granularity_options_days = null, $granularity_options_strategy = null, $tenant_id = null, string $contentType = self::contentTypes['tenantFilesInfoGetTenantFilesInfos'][0])
    {
        return $this->tenantFilesInfoGetTenantFilesInfosAsyncWithHttpInfo($start_time, $end_time, $granularity_options_days, $granularity_options_strategy, $tenant_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tenantFilesInfoGetTenantFilesInfosAsyncWithHttpInfo
     *
     * Returns information about file storage usage for the specified time period.
     *
     * @param  \DateTime $start_time Start date in UTC time format. (optional)
     * @param  \DateTime $end_time End date in UTC time format. If not specified, the current UTC time is used by default. (optional)
     * @param  int $granularity_options_days Number of days per group.  Set to &#x60;0&#x60; to keep the original array unchanged. (optional)
     * @param  \Aurigma\AssetStorage\Model\GranularityStrategyType $granularity_options_strategy Granularity calculation strategy. (optional)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tenantFilesInfoGetTenantFilesInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tenantFilesInfoGetTenantFilesInfosAsyncWithHttpInfo($start_time = null, $end_time = null, $granularity_options_days = null, $granularity_options_strategy = null, $tenant_id = null, string $contentType = self::contentTypes['tenantFilesInfoGetTenantFilesInfos'][0])
    {
        $returnType = '\Aurigma\AssetStorage\Model\TenantFilesInfoDto[]';
        $request = $this->tenantFilesInfoGetTenantFilesInfosRequest($start_time, $end_time, $granularity_options_days, $granularity_options_strategy, $tenant_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tenantFilesInfoGetTenantFilesInfos'
     *
     * @param  \DateTime $start_time Start date in UTC time format. (optional)
     * @param  \DateTime $end_time End date in UTC time format. If not specified, the current UTC time is used by default. (optional)
     * @param  int $granularity_options_days Number of days per group.  Set to &#x60;0&#x60; to keep the original array unchanged. (optional)
     * @param  \Aurigma\AssetStorage\Model\GranularityStrategyType $granularity_options_strategy Granularity calculation strategy. (optional)
     * @param  int $tenant_id Tenant ID. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tenantFilesInfoGetTenantFilesInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tenantFilesInfoGetTenantFilesInfosRequest($start_time = null, $end_time = null, $granularity_options_days = null, $granularity_options_strategy = null, $tenant_id = null, string $contentType = self::contentTypes['tenantFilesInfoGetTenantFilesInfos'][0])
    {







        $resourcePath = '/api/accounting-operational/v1/tenant-files-infos';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_time,
            'startTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_time,
            'endTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $granularity_options_days,
            'granularityOptions.days', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $granularity_options_strategy,
            'granularityOptions.strategy', // param base name
            'GranularityStrategyType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tenant_id,
            'tenantId', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
