<?php
/**
 * TraceGeneratorApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aurigma\AssetStorage\ApiException;
use Aurigma\AssetStorage\Configuration;
use Aurigma\AssetStorage\HeaderSelector;
use Aurigma\AssetStorage\ObjectSerializer;

/**
 * TraceGeneratorApi Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TraceGeneratorApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'traceGeneratorCreateAssetGenerationInfo' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'traceGeneratorCreateImageProcessingInfo' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'traceGeneratorCreateOutputFilesInfo' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'traceGeneratorCreateProjectInfo' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'traceGeneratorCreateRenderingInfo' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation traceGeneratorCreateAssetGenerationInfo
     *
     * Generates a trace with information about asset generation.
     *
     * @param  \Aurigma\AssetStorage\Model\AssetGenerationInfoDto $asset_generation_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateAssetGenerationInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function traceGeneratorCreateAssetGenerationInfo($asset_generation_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateAssetGenerationInfo'][0])
    {
        list($response) = $this->traceGeneratorCreateAssetGenerationInfoWithHttpInfo($asset_generation_info_dto, $contentType);
        return $response;
    }

    /**
     * Operation traceGeneratorCreateAssetGenerationInfoWithHttpInfo
     *
     * Generates a trace with information about asset generation.
     *
     * @param  \Aurigma\AssetStorage\Model\AssetGenerationInfoDto $asset_generation_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateAssetGenerationInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function traceGeneratorCreateAssetGenerationInfoWithHttpInfo($asset_generation_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateAssetGenerationInfo'][0])
    {
        $request = $this->traceGeneratorCreateAssetGenerationInfoRequest($asset_generation_info_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation traceGeneratorCreateAssetGenerationInfoAsync
     *
     * Generates a trace with information about asset generation.
     *
     * @param  \Aurigma\AssetStorage\Model\AssetGenerationInfoDto $asset_generation_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateAssetGenerationInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateAssetGenerationInfoAsync($asset_generation_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateAssetGenerationInfo'][0])
    {
        return $this->traceGeneratorCreateAssetGenerationInfoAsyncWithHttpInfo($asset_generation_info_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation traceGeneratorCreateAssetGenerationInfoAsyncWithHttpInfo
     *
     * Generates a trace with information about asset generation.
     *
     * @param  \Aurigma\AssetStorage\Model\AssetGenerationInfoDto $asset_generation_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateAssetGenerationInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateAssetGenerationInfoAsyncWithHttpInfo($asset_generation_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateAssetGenerationInfo'][0])
    {
        $returnType = 'string';
        $request = $this->traceGeneratorCreateAssetGenerationInfoRequest($asset_generation_info_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'traceGeneratorCreateAssetGenerationInfo'
     *
     * @param  \Aurigma\AssetStorage\Model\AssetGenerationInfoDto $asset_generation_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateAssetGenerationInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function traceGeneratorCreateAssetGenerationInfoRequest($asset_generation_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateAssetGenerationInfo'][0])
    {

        // verify the required parameter 'asset_generation_info_dto' is set
        if ($asset_generation_info_dto === null || (is_array($asset_generation_info_dto) && count($asset_generation_info_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $asset_generation_info_dto when calling traceGeneratorCreateAssetGenerationInfo'
            );
        }


        $resourcePath = '/api/accounting-tracing/v1/trace-generator/asset-generation-info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($asset_generation_info_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($asset_generation_info_dto));
            } else {
                $httpBody = $asset_generation_info_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation traceGeneratorCreateImageProcessingInfo
     *
     * Generates a trace with information about image processing.
     *
     * @param  \Aurigma\AssetStorage\Model\ImageProcessingInfoDto $image_processing_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateImageProcessingInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function traceGeneratorCreateImageProcessingInfo($image_processing_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateImageProcessingInfo'][0])
    {
        list($response) = $this->traceGeneratorCreateImageProcessingInfoWithHttpInfo($image_processing_info_dto, $contentType);
        return $response;
    }

    /**
     * Operation traceGeneratorCreateImageProcessingInfoWithHttpInfo
     *
     * Generates a trace with information about image processing.
     *
     * @param  \Aurigma\AssetStorage\Model\ImageProcessingInfoDto $image_processing_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateImageProcessingInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function traceGeneratorCreateImageProcessingInfoWithHttpInfo($image_processing_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateImageProcessingInfo'][0])
    {
        $request = $this->traceGeneratorCreateImageProcessingInfoRequest($image_processing_info_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation traceGeneratorCreateImageProcessingInfoAsync
     *
     * Generates a trace with information about image processing.
     *
     * @param  \Aurigma\AssetStorage\Model\ImageProcessingInfoDto $image_processing_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateImageProcessingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateImageProcessingInfoAsync($image_processing_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateImageProcessingInfo'][0])
    {
        return $this->traceGeneratorCreateImageProcessingInfoAsyncWithHttpInfo($image_processing_info_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation traceGeneratorCreateImageProcessingInfoAsyncWithHttpInfo
     *
     * Generates a trace with information about image processing.
     *
     * @param  \Aurigma\AssetStorage\Model\ImageProcessingInfoDto $image_processing_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateImageProcessingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateImageProcessingInfoAsyncWithHttpInfo($image_processing_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateImageProcessingInfo'][0])
    {
        $returnType = 'string';
        $request = $this->traceGeneratorCreateImageProcessingInfoRequest($image_processing_info_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'traceGeneratorCreateImageProcessingInfo'
     *
     * @param  \Aurigma\AssetStorage\Model\ImageProcessingInfoDto $image_processing_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateImageProcessingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function traceGeneratorCreateImageProcessingInfoRequest($image_processing_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateImageProcessingInfo'][0])
    {

        // verify the required parameter 'image_processing_info_dto' is set
        if ($image_processing_info_dto === null || (is_array($image_processing_info_dto) && count($image_processing_info_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $image_processing_info_dto when calling traceGeneratorCreateImageProcessingInfo'
            );
        }


        $resourcePath = '/api/accounting-tracing/v1/trace-generator/image-processing-info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($image_processing_info_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($image_processing_info_dto));
            } else {
                $httpBody = $image_processing_info_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation traceGeneratorCreateOutputFilesInfo
     *
     * Generates a trace with information about the output image files.
     *
     * @param  \Aurigma\AssetStorage\Model\OutputFilesInfoDto $output_files_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateOutputFilesInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aurigma\AssetStorage\Model\OutputFileInfo[]
     */
    public function traceGeneratorCreateOutputFilesInfo($output_files_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateOutputFilesInfo'][0])
    {
        list($response) = $this->traceGeneratorCreateOutputFilesInfoWithHttpInfo($output_files_info_dto, $contentType);
        return $response;
    }

    /**
     * Operation traceGeneratorCreateOutputFilesInfoWithHttpInfo
     *
     * Generates a trace with information about the output image files.
     *
     * @param  \Aurigma\AssetStorage\Model\OutputFilesInfoDto $output_files_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateOutputFilesInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aurigma\AssetStorage\Model\OutputFileInfo[], HTTP status code, HTTP response headers (array of strings)
     */
    public function traceGeneratorCreateOutputFilesInfoWithHttpInfo($output_files_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateOutputFilesInfo'][0])
    {
        $request = $this->traceGeneratorCreateOutputFilesInfoRequest($output_files_info_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\Aurigma\AssetStorage\Model\OutputFileInfo[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aurigma\AssetStorage\Model\OutputFileInfo[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aurigma\AssetStorage\Model\OutputFileInfo[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aurigma\AssetStorage\Model\OutputFileInfo[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aurigma\AssetStorage\Model\OutputFileInfo[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation traceGeneratorCreateOutputFilesInfoAsync
     *
     * Generates a trace with information about the output image files.
     *
     * @param  \Aurigma\AssetStorage\Model\OutputFilesInfoDto $output_files_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateOutputFilesInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateOutputFilesInfoAsync($output_files_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateOutputFilesInfo'][0])
    {
        return $this->traceGeneratorCreateOutputFilesInfoAsyncWithHttpInfo($output_files_info_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation traceGeneratorCreateOutputFilesInfoAsyncWithHttpInfo
     *
     * Generates a trace with information about the output image files.
     *
     * @param  \Aurigma\AssetStorage\Model\OutputFilesInfoDto $output_files_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateOutputFilesInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateOutputFilesInfoAsyncWithHttpInfo($output_files_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateOutputFilesInfo'][0])
    {
        $returnType = '\Aurigma\AssetStorage\Model\OutputFileInfo[]';
        $request = $this->traceGeneratorCreateOutputFilesInfoRequest($output_files_info_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'traceGeneratorCreateOutputFilesInfo'
     *
     * @param  \Aurigma\AssetStorage\Model\OutputFilesInfoDto $output_files_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateOutputFilesInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function traceGeneratorCreateOutputFilesInfoRequest($output_files_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateOutputFilesInfo'][0])
    {

        // verify the required parameter 'output_files_info_dto' is set
        if ($output_files_info_dto === null || (is_array($output_files_info_dto) && count($output_files_info_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $output_files_info_dto when calling traceGeneratorCreateOutputFilesInfo'
            );
        }


        $resourcePath = '/api/accounting-tracing/v1/trace-generator/output-files-info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($output_files_info_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($output_files_info_dto));
            } else {
                $httpBody = $output_files_info_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation traceGeneratorCreateProjectInfo
     *
     * Generates a trace with project information.
     *
     * @param  \Aurigma\AssetStorage\Model\ProjectInfoDto $project_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateProjectInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function traceGeneratorCreateProjectInfo($project_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateProjectInfo'][0])
    {
        list($response) = $this->traceGeneratorCreateProjectInfoWithHttpInfo($project_info_dto, $contentType);
        return $response;
    }

    /**
     * Operation traceGeneratorCreateProjectInfoWithHttpInfo
     *
     * Generates a trace with project information.
     *
     * @param  \Aurigma\AssetStorage\Model\ProjectInfoDto $project_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateProjectInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function traceGeneratorCreateProjectInfoWithHttpInfo($project_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateProjectInfo'][0])
    {
        $request = $this->traceGeneratorCreateProjectInfoRequest($project_info_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation traceGeneratorCreateProjectInfoAsync
     *
     * Generates a trace with project information.
     *
     * @param  \Aurigma\AssetStorage\Model\ProjectInfoDto $project_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateProjectInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateProjectInfoAsync($project_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateProjectInfo'][0])
    {
        return $this->traceGeneratorCreateProjectInfoAsyncWithHttpInfo($project_info_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation traceGeneratorCreateProjectInfoAsyncWithHttpInfo
     *
     * Generates a trace with project information.
     *
     * @param  \Aurigma\AssetStorage\Model\ProjectInfoDto $project_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateProjectInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateProjectInfoAsyncWithHttpInfo($project_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateProjectInfo'][0])
    {
        $returnType = 'string';
        $request = $this->traceGeneratorCreateProjectInfoRequest($project_info_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'traceGeneratorCreateProjectInfo'
     *
     * @param  \Aurigma\AssetStorage\Model\ProjectInfoDto $project_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateProjectInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function traceGeneratorCreateProjectInfoRequest($project_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateProjectInfo'][0])
    {

        // verify the required parameter 'project_info_dto' is set
        if ($project_info_dto === null || (is_array($project_info_dto) && count($project_info_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_info_dto when calling traceGeneratorCreateProjectInfo'
            );
        }


        $resourcePath = '/api/accounting-tracing/v1/trace-generator/project-info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($project_info_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($project_info_dto));
            } else {
                $httpBody = $project_info_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation traceGeneratorCreateRenderingInfo
     *
     * Generates a trace with rendering information.
     *
     * @param  \Aurigma\AssetStorage\Model\RenderingInfoDto $rendering_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateRenderingInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string
     */
    public function traceGeneratorCreateRenderingInfo($rendering_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateRenderingInfo'][0])
    {
        list($response) = $this->traceGeneratorCreateRenderingInfoWithHttpInfo($rendering_info_dto, $contentType);
        return $response;
    }

    /**
     * Operation traceGeneratorCreateRenderingInfoWithHttpInfo
     *
     * Generates a trace with rendering information.
     *
     * @param  \Aurigma\AssetStorage\Model\RenderingInfoDto $rendering_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateRenderingInfo'] to see the possible values for this operation
     *
     * @throws \Aurigma\AssetStorage\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function traceGeneratorCreateRenderingInfoWithHttpInfo($rendering_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateRenderingInfo'][0])
    {
        $request = $this->traceGeneratorCreateRenderingInfoRequest($rendering_info_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation traceGeneratorCreateRenderingInfoAsync
     *
     * Generates a trace with rendering information.
     *
     * @param  \Aurigma\AssetStorage\Model\RenderingInfoDto $rendering_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateRenderingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateRenderingInfoAsync($rendering_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateRenderingInfo'][0])
    {
        return $this->traceGeneratorCreateRenderingInfoAsyncWithHttpInfo($rendering_info_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation traceGeneratorCreateRenderingInfoAsyncWithHttpInfo
     *
     * Generates a trace with rendering information.
     *
     * @param  \Aurigma\AssetStorage\Model\RenderingInfoDto $rendering_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateRenderingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function traceGeneratorCreateRenderingInfoAsyncWithHttpInfo($rendering_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateRenderingInfo'][0])
    {
        $returnType = 'string';
        $request = $this->traceGeneratorCreateRenderingInfoRequest($rendering_info_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'traceGeneratorCreateRenderingInfo'
     *
     * @param  \Aurigma\AssetStorage\Model\RenderingInfoDto $rendering_info_dto Trace message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['traceGeneratorCreateRenderingInfo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function traceGeneratorCreateRenderingInfoRequest($rendering_info_dto, string $contentType = self::contentTypes['traceGeneratorCreateRenderingInfo'][0])
    {

        // verify the required parameter 'rendering_info_dto' is set
        if ($rendering_info_dto === null || (is_array($rendering_info_dto) && count($rendering_info_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $rendering_info_dto when calling traceGeneratorCreateRenderingInfo'
            );
        }


        $resourcePath = '/api/accounting-tracing/v1/trace-generator/rendering-info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($rendering_info_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($rendering_info_dto));
            } else {
                $httpBody = $rendering_info_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
