<?php
/**
 * AccountDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * AccountDto Class Doc Comment
 *
 * @category Class
 * @description Account details.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'tenant_id' => 'int',
        'is_active' => 'bool',
        'subscription_plan_sku' => 'string',
        'subscription_plan_name' => 'string',
        'activation_date' => '\DateTime',
        'deactivation_date' => '\DateTime',
        'month_count' => 'int',
        'credit_units_limit' => 'int',
        'file_storage_size_limit_in_gb' => 'int',
        'storefront_limit' => 'int',
        'account_period_infos' => '\Aurigma\AssetStorage\Model\AccountPeriodInfoDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'tenant_id' => 'int32',
        'is_active' => null,
        'subscription_plan_sku' => null,
        'subscription_plan_name' => null,
        'activation_date' => 'date-time',
        'deactivation_date' => 'date-time',
        'month_count' => 'int32',
        'credit_units_limit' => 'int64',
        'file_storage_size_limit_in_gb' => 'int32',
        'storefront_limit' => 'int32',
        'account_period_infos' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'tenant_id' => false,
        'is_active' => false,
        'subscription_plan_sku' => true,
        'subscription_plan_name' => true,
        'activation_date' => false,
        'deactivation_date' => true,
        'month_count' => false,
        'credit_units_limit' => false,
        'file_storage_size_limit_in_gb' => false,
        'storefront_limit' => true,
        'account_period_infos' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'tenant_id' => 'tenantId',
        'is_active' => 'isActive',
        'subscription_plan_sku' => 'subscriptionPlanSku',
        'subscription_plan_name' => 'subscriptionPlanName',
        'activation_date' => 'activationDate',
        'deactivation_date' => 'deactivationDate',
        'month_count' => 'monthCount',
        'credit_units_limit' => 'creditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'fileStorageSizeLimitInGb',
        'storefront_limit' => 'storefrontLimit',
        'account_period_infos' => 'accountPeriodInfos'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'tenant_id' => 'setTenantId',
        'is_active' => 'setIsActive',
        'subscription_plan_sku' => 'setSubscriptionPlanSku',
        'subscription_plan_name' => 'setSubscriptionPlanName',
        'activation_date' => 'setActivationDate',
        'deactivation_date' => 'setDeactivationDate',
        'month_count' => 'setMonthCount',
        'credit_units_limit' => 'setCreditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'setFileStorageSizeLimitInGb',
        'storefront_limit' => 'setStorefrontLimit',
        'account_period_infos' => 'setAccountPeriodInfos'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'tenant_id' => 'getTenantId',
        'is_active' => 'getIsActive',
        'subscription_plan_sku' => 'getSubscriptionPlanSku',
        'subscription_plan_name' => 'getSubscriptionPlanName',
        'activation_date' => 'getActivationDate',
        'deactivation_date' => 'getDeactivationDate',
        'month_count' => 'getMonthCount',
        'credit_units_limit' => 'getCreditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'getFileStorageSizeLimitInGb',
        'storefront_limit' => 'getStorefrontLimit',
        'account_period_infos' => 'getAccountPeriodInfos'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], null);
        $this->setIfExists('subscription_plan_sku', $data ?? [], null);
        $this->setIfExists('subscription_plan_name', $data ?? [], null);
        $this->setIfExists('activation_date', $data ?? [], null);
        $this->setIfExists('deactivation_date', $data ?? [], null);
        $this->setIfExists('month_count', $data ?? [], null);
        $this->setIfExists('credit_units_limit', $data ?? [], null);
        $this->setIfExists('file_storage_size_limit_in_gb', $data ?? [], null);
        $this->setIfExists('storefront_limit', $data ?? [], null);
        $this->setIfExists('account_period_infos', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Unique identifier.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id Tenant ID.
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool|null $is_active Indicates if the account is active.
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets subscription_plan_sku
     *
     * @return string|null
     */
    public function getSubscriptionPlanSku()
    {
        return $this->container['subscription_plan_sku'];
    }

    /**
     * Sets subscription_plan_sku
     *
     * @param string|null $subscription_plan_sku SKU of the subscription plan (if the account was created based on SKU).
     *
     * @return self
     */
    public function setSubscriptionPlanSku($subscription_plan_sku)
    {
        if (is_null($subscription_plan_sku)) {
            array_push($this->openAPINullablesSetToNull, 'subscription_plan_sku');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscription_plan_sku', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscription_plan_sku'] = $subscription_plan_sku;

        return $this;
    }

    /**
     * Gets subscription_plan_name
     *
     * @return string|null
     */
    public function getSubscriptionPlanName()
    {
        return $this->container['subscription_plan_name'];
    }

    /**
     * Sets subscription_plan_name
     *
     * @param string|null $subscription_plan_name Name of the subscription plan (if the account was created based on SKU).
     *
     * @return self
     */
    public function setSubscriptionPlanName($subscription_plan_name)
    {
        if (is_null($subscription_plan_name)) {
            array_push($this->openAPINullablesSetToNull, 'subscription_plan_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscription_plan_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscription_plan_name'] = $subscription_plan_name;

        return $this;
    }

    /**
     * Gets activation_date
     *
     * @return \DateTime|null
     */
    public function getActivationDate()
    {
        return $this->container['activation_date'];
    }

    /**
     * Sets activation_date
     *
     * @param \DateTime|null $activation_date Activation date in UTC time format.
     *
     * @return self
     */
    public function setActivationDate($activation_date)
    {
        if (is_null($activation_date)) {
            throw new \InvalidArgumentException('non-nullable activation_date cannot be null');
        }
        $this->container['activation_date'] = $activation_date;

        return $this;
    }

    /**
     * Gets deactivation_date
     *
     * @return \DateTime|null
     */
    public function getDeactivationDate()
    {
        return $this->container['deactivation_date'];
    }

    /**
     * Sets deactivation_date
     *
     * @param \DateTime|null $deactivation_date Deactivation date in UTC time format.
     *
     * @return self
     */
    public function setDeactivationDate($deactivation_date)
    {
        if (is_null($deactivation_date)) {
            array_push($this->openAPINullablesSetToNull, 'deactivation_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deactivation_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deactivation_date'] = $deactivation_date;

        return $this;
    }

    /**
     * Gets month_count
     *
     * @return int|null
     */
    public function getMonthCount()
    {
        return $this->container['month_count'];
    }

    /**
     * Sets month_count
     *
     * @param int|null $month_count The number of months in the accounting period.
     *
     * @return self
     */
    public function setMonthCount($month_count)
    {
        if (is_null($month_count)) {
            throw new \InvalidArgumentException('non-nullable month_count cannot be null');
        }
        $this->container['month_count'] = $month_count;

        return $this;
    }

    /**
     * Gets credit_units_limit
     *
     * @return int|null
     */
    public function getCreditUnitsLimit()
    {
        return $this->container['credit_units_limit'];
    }

    /**
     * Sets credit_units_limit
     *
     * @param int|null $credit_units_limit Credit units limit.
     *
     * @return self
     */
    public function setCreditUnitsLimit($credit_units_limit)
    {
        if (is_null($credit_units_limit)) {
            throw new \InvalidArgumentException('non-nullable credit_units_limit cannot be null');
        }
        $this->container['credit_units_limit'] = $credit_units_limit;

        return $this;
    }

    /**
     * Gets file_storage_size_limit_in_gb
     *
     * @return int|null
     */
    public function getFileStorageSizeLimitInGb()
    {
        return $this->container['file_storage_size_limit_in_gb'];
    }

    /**
     * Sets file_storage_size_limit_in_gb
     *
     * @param int|null $file_storage_size_limit_in_gb File storage limit in gigabytes (GB).
     *
     * @return self
     */
    public function setFileStorageSizeLimitInGb($file_storage_size_limit_in_gb)
    {
        if (is_null($file_storage_size_limit_in_gb)) {
            throw new \InvalidArgumentException('non-nullable file_storage_size_limit_in_gb cannot be null');
        }
        $this->container['file_storage_size_limit_in_gb'] = $file_storage_size_limit_in_gb;

        return $this;
    }

    /**
     * Gets storefront_limit
     *
     * @return int|null
     */
    public function getStorefrontLimit()
    {
        return $this->container['storefront_limit'];
    }

    /**
     * Sets storefront_limit
     *
     * @param int|null $storefront_limit Storefront limit.
     *
     * @return self
     */
    public function setStorefrontLimit($storefront_limit)
    {
        if (is_null($storefront_limit)) {
            array_push($this->openAPINullablesSetToNull, 'storefront_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('storefront_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['storefront_limit'] = $storefront_limit;

        return $this;
    }

    /**
     * Gets account_period_infos
     *
     * @return \Aurigma\AssetStorage\Model\AccountPeriodInfoDto[]|null
     */
    public function getAccountPeriodInfos()
    {
        return $this->container['account_period_infos'];
    }

    /**
     * Sets account_period_infos
     *
     * @param \Aurigma\AssetStorage\Model\AccountPeriodInfoDto[]|null $account_period_infos Account's periods.
     *
     * @return self
     */
    public function setAccountPeriodInfos($account_period_infos)
    {
        if (is_null($account_period_infos)) {
            array_push($this->openAPINullablesSetToNull, 'account_period_infos');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('account_period_infos', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['account_period_infos'] = $account_period_infos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


