<?php
/**
 * AccountPeriodInfoDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * AccountPeriodInfoDto Class Doc Comment
 *
 * @category Class
 * @description Information about the account&#39;s credits for the specified accounting period.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountPeriodInfoDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountPeriodInfoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'period' => '\Aurigma\AssetStorage\Model\AccountPeriodInfoDtoPeriod',
        'credit_units_spent' => 'int',
        'extra_credit_units' => 'int',
        'total_files_size_in_bytes' => 'int',
        'extra_file_storage_size_in_bytes' => 'int',
        'storefronts' => 'int',
        'extra_storefronts' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'period' => null,
        'credit_units_spent' => 'int64',
        'extra_credit_units' => 'int64',
        'total_files_size_in_bytes' => 'int64',
        'extra_file_storage_size_in_bytes' => 'int64',
        'storefronts' => 'int32',
        'extra_storefronts' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'period' => true,
        'credit_units_spent' => false,
        'extra_credit_units' => false,
        'total_files_size_in_bytes' => false,
        'extra_file_storage_size_in_bytes' => false,
        'storefronts' => true,
        'extra_storefronts' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'period' => 'period',
        'credit_units_spent' => 'creditUnitsSpent',
        'extra_credit_units' => 'extraCreditUnits',
        'total_files_size_in_bytes' => 'totalFilesSizeInBytes',
        'extra_file_storage_size_in_bytes' => 'extraFileStorageSizeInBytes',
        'storefronts' => 'storefronts',
        'extra_storefronts' => 'extraStorefronts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'period' => 'setPeriod',
        'credit_units_spent' => 'setCreditUnitsSpent',
        'extra_credit_units' => 'setExtraCreditUnits',
        'total_files_size_in_bytes' => 'setTotalFilesSizeInBytes',
        'extra_file_storage_size_in_bytes' => 'setExtraFileStorageSizeInBytes',
        'storefronts' => 'setStorefronts',
        'extra_storefronts' => 'setExtraStorefronts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'period' => 'getPeriod',
        'credit_units_spent' => 'getCreditUnitsSpent',
        'extra_credit_units' => 'getExtraCreditUnits',
        'total_files_size_in_bytes' => 'getTotalFilesSizeInBytes',
        'extra_file_storage_size_in_bytes' => 'getExtraFileStorageSizeInBytes',
        'storefronts' => 'getStorefronts',
        'extra_storefronts' => 'getExtraStorefronts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('credit_units_spent', $data ?? [], null);
        $this->setIfExists('extra_credit_units', $data ?? [], null);
        $this->setIfExists('total_files_size_in_bytes', $data ?? [], null);
        $this->setIfExists('extra_file_storage_size_in_bytes', $data ?? [], null);
        $this->setIfExists('storefronts', $data ?? [], null);
        $this->setIfExists('extra_storefronts', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets period
     *
     * @return \Aurigma\AssetStorage\Model\AccountPeriodInfoDtoPeriod|null
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param \Aurigma\AssetStorage\Model\AccountPeriodInfoDtoPeriod|null $period period
     *
     * @return self
     */
    public function setPeriod($period)
    {
        if (is_null($period)) {
            array_push($this->openAPINullablesSetToNull, 'period');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('period', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets credit_units_spent
     *
     * @return int|null
     */
    public function getCreditUnitsSpent()
    {
        return $this->container['credit_units_spent'];
    }

    /**
     * Sets credit_units_spent
     *
     * @param int|null $credit_units_spent Amount of credit units spent.
     *
     * @return self
     */
    public function setCreditUnitsSpent($credit_units_spent)
    {
        if (is_null($credit_units_spent)) {
            throw new \InvalidArgumentException('non-nullable credit_units_spent cannot be null');
        }
        $this->container['credit_units_spent'] = $credit_units_spent;

        return $this;
    }

    /**
     * Gets extra_credit_units
     *
     * @return int|null
     */
    public function getExtraCreditUnits()
    {
        return $this->container['extra_credit_units'];
    }

    /**
     * Sets extra_credit_units
     *
     * @param int|null $extra_credit_units Amount of extra credit units.
     *
     * @return self
     */
    public function setExtraCreditUnits($extra_credit_units)
    {
        if (is_null($extra_credit_units)) {
            throw new \InvalidArgumentException('non-nullable extra_credit_units cannot be null');
        }
        $this->container['extra_credit_units'] = $extra_credit_units;

        return $this;
    }

    /**
     * Gets total_files_size_in_bytes
     *
     * @return int|null
     */
    public function getTotalFilesSizeInBytes()
    {
        return $this->container['total_files_size_in_bytes'];
    }

    /**
     * Sets total_files_size_in_bytes
     *
     * @param int|null $total_files_size_in_bytes Total size of files in bytes.
     *
     * @return self
     */
    public function setTotalFilesSizeInBytes($total_files_size_in_bytes)
    {
        if (is_null($total_files_size_in_bytes)) {
            throw new \InvalidArgumentException('non-nullable total_files_size_in_bytes cannot be null');
        }
        $this->container['total_files_size_in_bytes'] = $total_files_size_in_bytes;

        return $this;
    }

    /**
     * Gets extra_file_storage_size_in_bytes
     *
     * @return int|null
     */
    public function getExtraFileStorageSizeInBytes()
    {
        return $this->container['extra_file_storage_size_in_bytes'];
    }

    /**
     * Sets extra_file_storage_size_in_bytes
     *
     * @param int|null $extra_file_storage_size_in_bytes Extra file storage size in bytes.
     *
     * @return self
     */
    public function setExtraFileStorageSizeInBytes($extra_file_storage_size_in_bytes)
    {
        if (is_null($extra_file_storage_size_in_bytes)) {
            throw new \InvalidArgumentException('non-nullable extra_file_storage_size_in_bytes cannot be null');
        }
        $this->container['extra_file_storage_size_in_bytes'] = $extra_file_storage_size_in_bytes;

        return $this;
    }

    /**
     * Gets storefronts
     *
     * @return int|null
     */
    public function getStorefronts()
    {
        return $this->container['storefronts'];
    }

    /**
     * Sets storefronts
     *
     * @param int|null $storefronts Amount of storefronts.
     *
     * @return self
     */
    public function setStorefronts($storefronts)
    {
        if (is_null($storefronts)) {
            array_push($this->openAPINullablesSetToNull, 'storefronts');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('storefronts', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['storefronts'] = $storefronts;

        return $this;
    }

    /**
     * Gets extra_storefronts
     *
     * @return int|null
     */
    public function getExtraStorefronts()
    {
        return $this->container['extra_storefronts'];
    }

    /**
     * Sets extra_storefronts
     *
     * @param int|null $extra_storefronts Amount of extra storefronts.
     *
     * @return self
     */
    public function setExtraStorefronts($extra_storefronts)
    {
        if (is_null($extra_storefronts)) {
            throw new \InvalidArgumentException('non-nullable extra_storefronts cannot be null');
        }
        $this->container['extra_storefronts'] = $extra_storefronts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


