<?php
/**
 * AssetGenerationInfoDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * AssetGenerationInfoDto Class Doc Comment
 *
 * @category Class
 * @description Information about asset generation.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AssetGenerationInfoDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AssetGenerationInfoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tenant_id' => 'int',
        'environment_id' => 'string',
        'asset_id' => 'string',
        'asset_type' => 'int',
        'spec_name' => 'string',
        'spec_group' => 'string',
        'spec_parameters' => 'string',
        'provider' => 'string',
        'licensed' => 'bool',
        'trace_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tenant_id' => 'int32',
        'environment_id' => null,
        'asset_id' => null,
        'asset_type' => 'int32',
        'spec_name' => null,
        'spec_group' => null,
        'spec_parameters' => null,
        'provider' => null,
        'licensed' => null,
        'trace_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tenant_id' => false,
        'environment_id' => true,
        'asset_id' => true,
        'asset_type' => false,
        'spec_name' => true,
        'spec_group' => true,
        'spec_parameters' => true,
        'provider' => true,
        'licensed' => false,
        'trace_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tenant_id' => 'tenantId',
        'environment_id' => 'environmentId',
        'asset_id' => 'assetId',
        'asset_type' => 'assetType',
        'spec_name' => 'specName',
        'spec_group' => 'specGroup',
        'spec_parameters' => 'specParameters',
        'provider' => 'provider',
        'licensed' => 'licensed',
        'trace_date' => 'traceDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tenant_id' => 'setTenantId',
        'environment_id' => 'setEnvironmentId',
        'asset_id' => 'setAssetId',
        'asset_type' => 'setAssetType',
        'spec_name' => 'setSpecName',
        'spec_group' => 'setSpecGroup',
        'spec_parameters' => 'setSpecParameters',
        'provider' => 'setProvider',
        'licensed' => 'setLicensed',
        'trace_date' => 'setTraceDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tenant_id' => 'getTenantId',
        'environment_id' => 'getEnvironmentId',
        'asset_id' => 'getAssetId',
        'asset_type' => 'getAssetType',
        'spec_name' => 'getSpecName',
        'spec_group' => 'getSpecGroup',
        'spec_parameters' => 'getSpecParameters',
        'provider' => 'getProvider',
        'licensed' => 'getLicensed',
        'trace_date' => 'getTraceDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('environment_id', $data ?? [], null);
        $this->setIfExists('asset_id', $data ?? [], null);
        $this->setIfExists('asset_type', $data ?? [], null);
        $this->setIfExists('spec_name', $data ?? [], null);
        $this->setIfExists('spec_group', $data ?? [], null);
        $this->setIfExists('spec_parameters', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('licensed', $data ?? [], null);
        $this->setIfExists('trace_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id Tenant ID.
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets environment_id
     *
     * @return string|null
     */
    public function getEnvironmentId()
    {
        return $this->container['environment_id'];
    }

    /**
     * Sets environment_id
     *
     * @param string|null $environment_id Environment ID.
     *
     * @return self
     */
    public function setEnvironmentId($environment_id)
    {
        if (is_null($environment_id)) {
            array_push($this->openAPINullablesSetToNull, 'environment_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('environment_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['environment_id'] = $environment_id;

        return $this;
    }

    /**
     * Gets asset_id
     *
     * @return string|null
     */
    public function getAssetId()
    {
        return $this->container['asset_id'];
    }

    /**
     * Sets asset_id
     *
     * @param string|null $asset_id Asset ID.
     *
     * @return self
     */
    public function setAssetId($asset_id)
    {
        if (is_null($asset_id)) {
            array_push($this->openAPINullablesSetToNull, 'asset_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('asset_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['asset_id'] = $asset_id;

        return $this;
    }

    /**
     * Gets asset_type
     *
     * @return int|null
     */
    public function getAssetType()
    {
        return $this->container['asset_type'];
    }

    /**
     * Sets asset_type
     *
     * @param int|null $asset_type Asset type.
     *
     * @return self
     */
    public function setAssetType($asset_type)
    {
        if (is_null($asset_type)) {
            throw new \InvalidArgumentException('non-nullable asset_type cannot be null');
        }
        $this->container['asset_type'] = $asset_type;

        return $this;
    }

    /**
     * Gets spec_name
     *
     * @return string|null
     */
    public function getSpecName()
    {
        return $this->container['spec_name'];
    }

    /**
     * Sets spec_name
     *
     * @param string|null $spec_name Specification name.
     *
     * @return self
     */
    public function setSpecName($spec_name)
    {
        if (is_null($spec_name)) {
            array_push($this->openAPINullablesSetToNull, 'spec_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spec_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spec_name'] = $spec_name;

        return $this;
    }

    /**
     * Gets spec_group
     *
     * @return string|null
     */
    public function getSpecGroup()
    {
        return $this->container['spec_group'];
    }

    /**
     * Sets spec_group
     *
     * @param string|null $spec_group Specification group.
     *
     * @return self
     */
    public function setSpecGroup($spec_group)
    {
        if (is_null($spec_group)) {
            array_push($this->openAPINullablesSetToNull, 'spec_group');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spec_group', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spec_group'] = $spec_group;

        return $this;
    }

    /**
     * Gets spec_parameters
     *
     * @return string|null
     */
    public function getSpecParameters()
    {
        return $this->container['spec_parameters'];
    }

    /**
     * Sets spec_parameters
     *
     * @param string|null $spec_parameters Specification parameters.  It's the serialized value of `Dictionary{string,string}`.  The parameter name is used as the key, and the value is used as the value.  For example: `'{\\\"L\\\":\"10\",\\\"W\\\":\"20\",\\\"H\\\":\"30\"}'`.
     *
     * @return self
     */
    public function setSpecParameters($spec_parameters)
    {
        if (is_null($spec_parameters)) {
            array_push($this->openAPINullablesSetToNull, 'spec_parameters');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spec_parameters', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spec_parameters'] = $spec_parameters;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return string|null
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param string|null $provider Provider.
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            array_push($this->openAPINullablesSetToNull, 'provider');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('provider', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets licensed
     *
     * @return bool|null
     */
    public function getLicensed()
    {
        return $this->container['licensed'];
    }

    /**
     * Sets licensed
     *
     * @param bool|null $licensed Indicates if a license is required.
     *
     * @return self
     */
    public function setLicensed($licensed)
    {
        if (is_null($licensed)) {
            throw new \InvalidArgumentException('non-nullable licensed cannot be null');
        }
        $this->container['licensed'] = $licensed;

        return $this;
    }

    /**
     * Gets trace_date
     *
     * @return \DateTime|null
     */
    public function getTraceDate()
    {
        return $this->container['trace_date'];
    }

    /**
     * Sets trace_date
     *
     * @param \DateTime|null $trace_date Date the trace was generated.
     *
     * @return self
     */
    public function setTraceDate($trace_date)
    {
        if (is_null($trace_date)) {
            throw new \InvalidArgumentException('non-nullable trace_date cannot be null');
        }
        $this->container['trace_date'] = $trace_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


