<?php
/**
 * ImageProcessingVendorType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * ImageProcessingVendorType Class Doc Comment
 *
 * @category Class
 * @description Type of image processing vendor.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageProcessingVendorType
{
    /**
     * Possible values of this enum
     */
    public const VECTORIZER_AI = 'VectorizerAi';

    public const OPEN_AI = 'OpenAi';

    public const PICSART = 'Picsart';

    public const REMOVE_BG = 'RemoveBg';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VECTORIZER_AI,
            self::OPEN_AI,
            self::PICSART,
            self::REMOVE_BG
        ];
    }
}


