<?php
/**
 * ImageProcessingOperationType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * ImageProcessingOperationType Class Doc Comment
 *
 * @category Class
 * @description Type of image processing operation.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageProcessingOperationType
{
    /**
     * Possible values of this enum
     */
    public const GENERATE_BY_TEXT = 'GenerateByText';

    public const REMOVE_BACKGROUND = 'RemoveBackground';

    public const UPSCALE = 'Upscale';

    public const VECTORIZE = 'Vectorize';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GENERATE_BY_TEXT,
            self::REMOVE_BACKGROUND,
            self::UPSCALE,
            self::VECTORIZE
        ];
    }
}


