<?php
/**
 * OutputFileInfo
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * OutputFileInfo Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class OutputFileInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OutputFileInfo';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'job_id' => 'string',
        'project_id' => 'int',
        'project_item_id' => 'int',
        'tenant_id' => 'int',
        'file_name' => 'string',
        'credit_units_spent' => 'int',
        'file_page_count' => 'int',
        'total_pages_area' => 'int',
        'file_pages_infos' => '\Aurigma\AssetStorage\Model\OutputFilePageInfo[]',
        'trace_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'job_id' => null,
        'project_id' => 'int32',
        'project_item_id' => 'int32',
        'tenant_id' => 'int32',
        'file_name' => null,
        'credit_units_spent' => 'int64',
        'file_page_count' => 'int32',
        'total_pages_area' => 'int64',
        'file_pages_infos' => null,
        'trace_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'job_id' => true,
        'project_id' => false,
        'project_item_id' => false,
        'tenant_id' => false,
        'file_name' => true,
        'credit_units_spent' => false,
        'file_page_count' => false,
        'total_pages_area' => false,
        'file_pages_infos' => true,
        'trace_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'job_id' => 'jobId',
        'project_id' => 'projectId',
        'project_item_id' => 'projectItemId',
        'tenant_id' => 'tenantId',
        'file_name' => 'fileName',
        'credit_units_spent' => 'creditUnitsSpent',
        'file_page_count' => 'filePageCount',
        'total_pages_area' => 'totalPagesArea',
        'file_pages_infos' => 'filePagesInfos',
        'trace_date' => 'traceDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'job_id' => 'setJobId',
        'project_id' => 'setProjectId',
        'project_item_id' => 'setProjectItemId',
        'tenant_id' => 'setTenantId',
        'file_name' => 'setFileName',
        'credit_units_spent' => 'setCreditUnitsSpent',
        'file_page_count' => 'setFilePageCount',
        'total_pages_area' => 'setTotalPagesArea',
        'file_pages_infos' => 'setFilePagesInfos',
        'trace_date' => 'setTraceDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'job_id' => 'getJobId',
        'project_id' => 'getProjectId',
        'project_item_id' => 'getProjectItemId',
        'tenant_id' => 'getTenantId',
        'file_name' => 'getFileName',
        'credit_units_spent' => 'getCreditUnitsSpent',
        'file_page_count' => 'getFilePageCount',
        'total_pages_area' => 'getTotalPagesArea',
        'file_pages_infos' => 'getFilePagesInfos',
        'trace_date' => 'getTraceDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('job_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('project_item_id', $data ?? [], null);
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('file_name', $data ?? [], null);
        $this->setIfExists('credit_units_spent', $data ?? [], null);
        $this->setIfExists('file_page_count', $data ?? [], null);
        $this->setIfExists('total_pages_area', $data ?? [], null);
        $this->setIfExists('file_pages_infos', $data ?? [], null);
        $this->setIfExists('trace_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets job_id
     *
     * @return string|null
     */
    public function getJobId()
    {
        return $this->container['job_id'];
    }

    /**
     * Sets job_id
     *
     * @param string|null $job_id job_id
     *
     * @return self
     */
    public function setJobId($job_id)
    {
        if (is_null($job_id)) {
            array_push($this->openAPINullablesSetToNull, 'job_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('job_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['job_id'] = $job_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return int|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param int|null $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets project_item_id
     *
     * @return int|null
     */
    public function getProjectItemId()
    {
        return $this->container['project_item_id'];
    }

    /**
     * Sets project_item_id
     *
     * @param int|null $project_item_id project_item_id
     *
     * @return self
     */
    public function setProjectItemId($project_item_id)
    {
        if (is_null($project_item_id)) {
            throw new \InvalidArgumentException('non-nullable project_item_id cannot be null');
        }
        $this->container['project_item_id'] = $project_item_id;

        return $this;
    }

    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id tenant_id
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets file_name
     *
     * @return string|null
     */
    public function getFileName()
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     *
     * @param string|null $file_name file_name
     *
     * @return self
     */
    public function setFileName($file_name)
    {
        if (is_null($file_name)) {
            array_push($this->openAPINullablesSetToNull, 'file_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('file_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets credit_units_spent
     *
     * @return int|null
     */
    public function getCreditUnitsSpent()
    {
        return $this->container['credit_units_spent'];
    }

    /**
     * Sets credit_units_spent
     *
     * @param int|null $credit_units_spent credit_units_spent
     *
     * @return self
     */
    public function setCreditUnitsSpent($credit_units_spent)
    {
        if (is_null($credit_units_spent)) {
            throw new \InvalidArgumentException('non-nullable credit_units_spent cannot be null');
        }
        $this->container['credit_units_spent'] = $credit_units_spent;

        return $this;
    }

    /**
     * Gets file_page_count
     *
     * @return int|null
     */
    public function getFilePageCount()
    {
        return $this->container['file_page_count'];
    }

    /**
     * Sets file_page_count
     *
     * @param int|null $file_page_count file_page_count
     *
     * @return self
     */
    public function setFilePageCount($file_page_count)
    {
        if (is_null($file_page_count)) {
            throw new \InvalidArgumentException('non-nullable file_page_count cannot be null');
        }
        $this->container['file_page_count'] = $file_page_count;

        return $this;
    }

    /**
     * Gets total_pages_area
     *
     * @return int|null
     */
    public function getTotalPagesArea()
    {
        return $this->container['total_pages_area'];
    }

    /**
     * Sets total_pages_area
     *
     * @param int|null $total_pages_area total_pages_area
     *
     * @return self
     */
    public function setTotalPagesArea($total_pages_area)
    {
        if (is_null($total_pages_area)) {
            throw new \InvalidArgumentException('non-nullable total_pages_area cannot be null');
        }
        $this->container['total_pages_area'] = $total_pages_area;

        return $this;
    }

    /**
     * Gets file_pages_infos
     *
     * @return \Aurigma\AssetStorage\Model\OutputFilePageInfo[]|null
     */
    public function getFilePagesInfos()
    {
        return $this->container['file_pages_infos'];
    }

    /**
     * Sets file_pages_infos
     *
     * @param \Aurigma\AssetStorage\Model\OutputFilePageInfo[]|null $file_pages_infos file_pages_infos
     *
     * @return self
     */
    public function setFilePagesInfos($file_pages_infos)
    {
        if (is_null($file_pages_infos)) {
            array_push($this->openAPINullablesSetToNull, 'file_pages_infos');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('file_pages_infos', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['file_pages_infos'] = $file_pages_infos;

        return $this;
    }

    /**
     * Gets trace_date
     *
     * @return \DateTime|null
     */
    public function getTraceDate()
    {
        return $this->container['trace_date'];
    }

    /**
     * Sets trace_date
     *
     * @param \DateTime|null $trace_date trace_date
     *
     * @return self
     */
    public function setTraceDate($trace_date)
    {
        if (is_null($trace_date)) {
            throw new \InvalidArgumentException('non-nullable trace_date cannot be null');
        }
        $this->container['trace_date'] = $trace_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


