<?php
/**
 * ProjectInfoDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * ProjectInfoDto Class Doc Comment
 *
 * @category Class
 * @description Information about the created project.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectInfoDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectInfoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tenant_id' => 'int',
        'project_id' => 'int',
        'project_item_id' => 'int',
        'ecommerce_system_type' => 'int',
        'storefront_id' => 'int',
        'storefront_product_reference' => 'string',
        'product_specification_id' => 'int',
        'pim_product_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tenant_id' => 'int32',
        'project_id' => 'int32',
        'project_item_id' => 'int32',
        'ecommerce_system_type' => 'int32',
        'storefront_id' => 'int32',
        'storefront_product_reference' => null,
        'product_specification_id' => 'int32',
        'pim_product_id' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tenant_id' => false,
        'project_id' => false,
        'project_item_id' => false,
        'ecommerce_system_type' => false,
        'storefront_id' => false,
        'storefront_product_reference' => true,
        'product_specification_id' => true,
        'pim_product_id' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tenant_id' => 'tenantId',
        'project_id' => 'projectId',
        'project_item_id' => 'projectItemId',
        'ecommerce_system_type' => 'ecommerceSystemType',
        'storefront_id' => 'storefrontId',
        'storefront_product_reference' => 'storefrontProductReference',
        'product_specification_id' => 'productSpecificationId',
        'pim_product_id' => 'pimProductId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tenant_id' => 'setTenantId',
        'project_id' => 'setProjectId',
        'project_item_id' => 'setProjectItemId',
        'ecommerce_system_type' => 'setEcommerceSystemType',
        'storefront_id' => 'setStorefrontId',
        'storefront_product_reference' => 'setStorefrontProductReference',
        'product_specification_id' => 'setProductSpecificationId',
        'pim_product_id' => 'setPimProductId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tenant_id' => 'getTenantId',
        'project_id' => 'getProjectId',
        'project_item_id' => 'getProjectItemId',
        'ecommerce_system_type' => 'getEcommerceSystemType',
        'storefront_id' => 'getStorefrontId',
        'storefront_product_reference' => 'getStorefrontProductReference',
        'product_specification_id' => 'getProductSpecificationId',
        'pim_product_id' => 'getPimProductId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tenant_id', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('project_item_id', $data ?? [], null);
        $this->setIfExists('ecommerce_system_type', $data ?? [], null);
        $this->setIfExists('storefront_id', $data ?? [], null);
        $this->setIfExists('storefront_product_reference', $data ?? [], null);
        $this->setIfExists('product_specification_id', $data ?? [], null);
        $this->setIfExists('pim_product_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tenant_id
     *
     * @return int|null
     */
    public function getTenantId()
    {
        return $this->container['tenant_id'];
    }

    /**
     * Sets tenant_id
     *
     * @param int|null $tenant_id Tenant ID.
     *
     * @return self
     */
    public function setTenantId($tenant_id)
    {
        if (is_null($tenant_id)) {
            throw new \InvalidArgumentException('non-nullable tenant_id cannot be null');
        }
        $this->container['tenant_id'] = $tenant_id;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return int|null
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param int|null $project_id Project ID.
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets project_item_id
     *
     * @return int|null
     */
    public function getProjectItemId()
    {
        return $this->container['project_item_id'];
    }

    /**
     * Sets project_item_id
     *
     * @param int|null $project_item_id Project item ID.
     *
     * @return self
     */
    public function setProjectItemId($project_item_id)
    {
        if (is_null($project_item_id)) {
            throw new \InvalidArgumentException('non-nullable project_item_id cannot be null');
        }
        $this->container['project_item_id'] = $project_item_id;

        return $this;
    }

    /**
     * Gets ecommerce_system_type
     *
     * @return int|null
     */
    public function getEcommerceSystemType()
    {
        return $this->container['ecommerce_system_type'];
    }

    /**
     * Sets ecommerce_system_type
     *
     * @param int|null $ecommerce_system_type Type of ecommerce system.
     *
     * @return self
     */
    public function setEcommerceSystemType($ecommerce_system_type)
    {
        if (is_null($ecommerce_system_type)) {
            throw new \InvalidArgumentException('non-nullable ecommerce_system_type cannot be null');
        }
        $this->container['ecommerce_system_type'] = $ecommerce_system_type;

        return $this;
    }

    /**
     * Gets storefront_id
     *
     * @return int|null
     */
    public function getStorefrontId()
    {
        return $this->container['storefront_id'];
    }

    /**
     * Sets storefront_id
     *
     * @param int|null $storefront_id Storefront ID.
     *
     * @return self
     */
    public function setStorefrontId($storefront_id)
    {
        if (is_null($storefront_id)) {
            throw new \InvalidArgumentException('non-nullable storefront_id cannot be null');
        }
        $this->container['storefront_id'] = $storefront_id;

        return $this;
    }

    /**
     * Gets storefront_product_reference
     *
     * @return string|null
     */
    public function getStorefrontProductReference()
    {
        return $this->container['storefront_product_reference'];
    }

    /**
     * Sets storefront_product_reference
     *
     * @param string|null $storefront_product_reference Storefront product ID.
     *
     * @return self
     */
    public function setStorefrontProductReference($storefront_product_reference)
    {
        if (is_null($storefront_product_reference)) {
            array_push($this->openAPINullablesSetToNull, 'storefront_product_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('storefront_product_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['storefront_product_reference'] = $storefront_product_reference;

        return $this;
    }

    /**
     * Gets product_specification_id
     *
     * @return int|null
     */
    public function getProductSpecificationId()
    {
        return $this->container['product_specification_id'];
    }

    /**
     * Sets product_specification_id
     *
     * @param int|null $product_specification_id Product specification (template) ID.
     *
     * @return self
     */
    public function setProductSpecificationId($product_specification_id)
    {
        if (is_null($product_specification_id)) {
            array_push($this->openAPINullablesSetToNull, 'product_specification_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_specification_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['product_specification_id'] = $product_specification_id;

        return $this;
    }

    /**
     * Gets pim_product_id
     *
     * @return int|null
     */
    public function getPimProductId()
    {
        return $this->container['pim_product_id'];
    }

    /**
     * Sets pim_product_id
     *
     * @param int|null $pim_product_id PIM Product ID.
     *
     * @return self
     */
    public function setPimProductId($pim_product_id)
    {
        if (is_null($pim_product_id)) {
            array_push($this->openAPINullablesSetToNull, 'pim_product_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('pim_product_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['pim_product_id'] = $pim_product_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


