<?php
/**
 * SubscriptionPlanCreationModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Accounting Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetStorage\Model;

use \ArrayAccess;
use \Aurigma\AssetStorage\ObjectSerializer;

/**
 * SubscriptionPlanCreationModel Class Doc Comment
 *
 * @category Class
 * @description Model for creating a subscription plan.
 * @package  Aurigma\AssetStorage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SubscriptionPlanCreationModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SubscriptionPlanCreationModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'sku' => 'string',
        'name' => 'string',
        'month_count' => 'int',
        'price' => 'int',
        'credit_units_limit' => 'int',
        'file_storage_size_limit_in_gb' => 'int',
        'storefront_limit' => 'int',
        'archived_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'sku' => null,
        'name' => null,
        'month_count' => 'int32',
        'price' => 'int32',
        'credit_units_limit' => 'int64',
        'file_storage_size_limit_in_gb' => 'int32',
        'storefront_limit' => 'int32',
        'archived_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'sku' => false,
        'name' => false,
        'month_count' => false,
        'price' => false,
        'credit_units_limit' => false,
        'file_storage_size_limit_in_gb' => false,
        'storefront_limit' => true,
        'archived_date' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sku' => 'sku',
        'name' => 'name',
        'month_count' => 'monthCount',
        'price' => 'price',
        'credit_units_limit' => 'creditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'fileStorageSizeLimitInGb',
        'storefront_limit' => 'storefrontLimit',
        'archived_date' => 'archivedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sku' => 'setSku',
        'name' => 'setName',
        'month_count' => 'setMonthCount',
        'price' => 'setPrice',
        'credit_units_limit' => 'setCreditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'setFileStorageSizeLimitInGb',
        'storefront_limit' => 'setStorefrontLimit',
        'archived_date' => 'setArchivedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sku' => 'getSku',
        'name' => 'getName',
        'month_count' => 'getMonthCount',
        'price' => 'getPrice',
        'credit_units_limit' => 'getCreditUnitsLimit',
        'file_storage_size_limit_in_gb' => 'getFileStorageSizeLimitInGb',
        'storefront_limit' => 'getStorefrontLimit',
        'archived_date' => 'getArchivedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('sku', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('month_count', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('credit_units_limit', $data ?? [], null);
        $this->setIfExists('file_storage_size_limit_in_gb', $data ?? [], null);
        $this->setIfExists('storefront_limit', $data ?? [], null);
        $this->setIfExists('archived_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['sku'] === null) {
            $invalidProperties[] = "'sku' can't be null";
        }
        if ((mb_strlen($this->container['sku']) < 1)) {
            $invalidProperties[] = "invalid value for 'sku', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string $sku Unique SKU.
     *
     * @return self
     */
    public function setSku($sku)
    {
        if (is_null($sku)) {
            throw new \InvalidArgumentException('non-nullable sku cannot be null');
        }

        if ((mb_strlen($sku) < 1)) {
            throw new \InvalidArgumentException('invalid length for $sku when calling SubscriptionPlanCreationModel., must be bigger than or equal to 1.');
        }

        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Unique name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling SubscriptionPlanCreationModel., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets month_count
     *
     * @return int|null
     */
    public function getMonthCount()
    {
        return $this->container['month_count'];
    }

    /**
     * Sets month_count
     *
     * @param int|null $month_count The number of months in the accounting period.
     *
     * @return self
     */
    public function setMonthCount($month_count)
    {
        if (is_null($month_count)) {
            throw new \InvalidArgumentException('non-nullable month_count cannot be null');
        }
        $this->container['month_count'] = $month_count;

        return $this;
    }

    /**
     * Gets price
     *
     * @return int|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param int|null $price Price.
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets credit_units_limit
     *
     * @return int|null
     */
    public function getCreditUnitsLimit()
    {
        return $this->container['credit_units_limit'];
    }

    /**
     * Sets credit_units_limit
     *
     * @param int|null $credit_units_limit Credit units limit.
     *
     * @return self
     */
    public function setCreditUnitsLimit($credit_units_limit)
    {
        if (is_null($credit_units_limit)) {
            throw new \InvalidArgumentException('non-nullable credit_units_limit cannot be null');
        }
        $this->container['credit_units_limit'] = $credit_units_limit;

        return $this;
    }

    /**
     * Gets file_storage_size_limit_in_gb
     *
     * @return int|null
     */
    public function getFileStorageSizeLimitInGb()
    {
        return $this->container['file_storage_size_limit_in_gb'];
    }

    /**
     * Sets file_storage_size_limit_in_gb
     *
     * @param int|null $file_storage_size_limit_in_gb File storage limit in gigabytes (GB).
     *
     * @return self
     */
    public function setFileStorageSizeLimitInGb($file_storage_size_limit_in_gb)
    {
        if (is_null($file_storage_size_limit_in_gb)) {
            throw new \InvalidArgumentException('non-nullable file_storage_size_limit_in_gb cannot be null');
        }
        $this->container['file_storage_size_limit_in_gb'] = $file_storage_size_limit_in_gb;

        return $this;
    }

    /**
     * Gets storefront_limit
     *
     * @return int|null
     */
    public function getStorefrontLimit()
    {
        return $this->container['storefront_limit'];
    }

    /**
     * Sets storefront_limit
     *
     * @param int|null $storefront_limit Storefront limit.
     *
     * @return self
     */
    public function setStorefrontLimit($storefront_limit)
    {
        if (is_null($storefront_limit)) {
            array_push($this->openAPINullablesSetToNull, 'storefront_limit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('storefront_limit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['storefront_limit'] = $storefront_limit;

        return $this;
    }

    /**
     * Gets archived_date
     *
     * @return \DateTime|null
     */
    public function getArchivedDate()
    {
        return $this->container['archived_date'];
    }

    /**
     * Sets archived_date
     *
     * @param \DateTime|null $archived_date Date and time when the subscription plan was archived, or `null` if the plan is active.
     *
     * @return self
     */
    public function setArchivedDate($archived_date)
    {
        if (is_null($archived_date)) {
            array_push($this->openAPINullablesSetToNull, 'archived_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('archived_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['archived_date'] = $archived_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


